@startuml CU1
actor Estudiante

rectangle "CU1: Consultar Examen" {
    usecase UC_ValidarCredenciales as "Validar usuario"
    usecase UC_ListarExamenes as "Mostrar listado de exámenes"
    usecase UC_SeleccionarExamen as "Seleccionar un examen"
    usecase UC_VerDetallesExamen as "Mostrar detalles del examen"
}

Estudiante -> UC_ValidarCredenciales
UC_ValidarCredenciales --> UC_ListarExamenes
UC_ListarExamenes --> UC_SeleccionarExamen
UC_SeleccionarExamen --> UC_VerDetallesExamen
@enduml
